In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('enzyme.csv')

In [4]:
df

seq_id                                   protein_sequence   pH  \
0           0  AAAAKAAALALLGEAPEVVDIWLPAGWRQPFRVFRLERKGDGVLVG...  7.0   
1           1  AAADGEPLHNEEERAGAGQVGRSLPQESEEQRTGSRPRRRRDLGSR...  7.0   
2           2  AAAFSTPRATSYRILSSAGSGSTRADAPQVRRLHTTRDLLAKDYYA...  7.0   
3           3  AAASGLRTAIPAQPLRHLLQPAPRPCLRPFGLLSVRAGSARRSGLL...  7.0   
4           4  AAATKSGPRRQSQGASVRTFTPFYFLVEPVDTLSVRGSSVILNCSA...  7.0   
...       ...                                                ...  ...   
31385   31385  YYMYSGGGSALAAGGGGAGRKGDWNDIDSIKKKDLHHSRGDEKAQG...  7.0   
31386   31386  YYNDQHRLSSYSVETAMFLSWERAIVKPGAMFKKAVIGFNCNVDLI...  7.0   
31387   31387  YYQRTLGAELLYKISFGEMPKSAQDSAENCPSGMQFPDTAIAHANV...  7.0   
31388   31388  YYSFSDNITTVFLSRQAIDDDHSLSLGTISDVVESENGVVAADDAR...  7.0   
31389   31389  YYVPDEYWQSLEVAHKLTFGYGYLTWEWVQGIRSYVYPLLIAGLYK...  7.0   

                             data_source    tm  
0      doi.org/10.1038/s41592-020-0801-4  75.7  
1      doi.org/10.1038/s41592-020-0801-4  50.5  
2      doi.org/10.1038/s41592-020-0801-4  40.5  
3      doi.org/10.1038/s41592-020-0801-4  47.2  
4      doi.org/10.1038/s41592-020-0801-4  49.5  
...                                  ...   ...  
31385  doi.org/10.1038/s41592-020-0801-4  51.8  
31386  doi.org/10.1038/s41592-020-0801-4  37.2  
31387  doi.org/10.1038/s41592-020-0801-4  64.6  
31388  doi.org/10.1038/s41592-020-0801-4  50.7  
31389  doi.org/10.1038/s41592-020-0801-4  37.6  

[31390 rows x 5 columns]

In [5]:
df.describe()

seq_id            pH            tm
count  31390.000000  31104.000000  31390.000000
mean   15694.500000      6.892339     49.147337
std     9061.656811      1.612225     14.010089
min        0.000000      1.990000     -1.000000
25%     7847.250000      7.000000     42.100000
50%    15694.500000      7.000000     48.000000
75%    23541.750000      7.000000     53.800000
max    31389.000000     64.900000    130.000000

In [6]:
df_new = df.drop(['pH'], axis =1 )

In [7]:
def get_kmers_count(pro, size=6):
    return [pro[i-size:i].lower() for i in range(size, len(pro))]

In [8]:
df['words'] = df.apply(lambda x: get_kmers_count(x['protein_sequence']), axis = 1)

In [9]:
df['words']

0        [aaaaka, aaakaa, aakaaa, akaaal, kaaala, aaala...
1        [aaadge, aadgep, adgepl, dgeplh, geplhn, eplhn...
2        [aaafst, aafstp, afstpr, fstpra, stprat, tprat...
3        [aaasgl, aasglr, asglrt, sglrta, glrtai, lrtai...
4        [aaatks, aatksg, atksgp, tksgpr, ksgprr, sgprr...
                               ...                        
31385    [yymysg, ymysgg, mysggg, ysgggs, sgggsa, gggsa...
31386    [yyndqh, yndqhr, ndqhrl, dqhrls, qhrlss, hrlss...
31387    [yyqrtl, yqrtlg, qrtlga, rtlgae, tlgael, lgael...
31388    [yysfsd, ysfsdn, sfsdni, fsdnit, sdnitt, dnitt...
31389    [yyvpde, yvpdey, vpdeyw, pdeywq, deywqs, eywqs...
Name: words, Length: 31390, dtype: object

In [10]:
import tensorflow as tf

In [11]:
tf.__version__

'2.6.5'

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [13]:
##for embedding layer
voc_size = 5000

In [14]:
pro_text = list(df['words'])
for item in range(len(pro_text)):
    pro_text[item]=' '.join(pro_text[item])

In [15]:
onehot_repr = [one_hot(words,voc_size) for words in pro_text]

In [16]:
max_len = len(max(df['words']))

In [17]:
max_len

531

In [18]:
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = max_len)

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [20]:
y_train = df['tm']

In [21]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=max_len))
model.add(LSTM(100))
model.add(Dense(1, activation='ReLU'))
model.compile(loss='mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])



In [22]:
x_train = np.array(embedded_docs)

In [23]:
x_train.shape

(31390, 531)

In [24]:
y_train.shape

(31390,)

In [25]:
from sklearn.model_selection import train_test_split
x,x_test,y,  y_test = train_test_split(x_train, y_train, test_size=0.9, random_state=365)


In [26]:
model.fit(x,y, validation_data=(x_test,y_test),epochs=10, batch_size=64)

2023-01-07 17:07:14.173441: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/10
50/50 [==============================] - 193s 4s/step - loss: 1857.7379 - accuracy: 0.0000e+00 - val_loss: 1301.6206 - val_accuracy: 0.0000e+00
Epoch 2/10
50/50 [==============================] - 163s 3s/step - loss: 1144.2471 - accuracy: 0.0000e+00 - val_loss: 960.7889 - val_accuracy: 0.0000e+00
Epoch 3/10
50/50 [==============================] - 168s 3s/step - loss: 858.3697 - accuracy: 0.0000e+00 - val_loss: 726.0231 - val_accuracy: 0.0000e+00
Epoch 4/10
50/50 [==============================] - 160s 3s/step - loss: 655.8055 - accuracy: 0.0000e+00 - val_loss: 558.0879 - val_accuracy: 0.0000e+00
Epoch 5/10
50/50 [==============================] - 165s 3s/step - loss: 508.2346 - accuracy: 0.0000e+00 - val_loss: 435.2749 - val_accuracy: 0.0000e+00
Epoch 6/10
50/50 [==============================] - 155s 3s/step - loss: 403.5496 - accuracy: 0.0000e+00 - val_loss: 350.1046 - val_accuracy: 0.0000e+00
Epoch 7/10
50/50 [==============================] - 156s 3s/step - loss: 330.71

In [72]:
y_pred = model.predict(x_test)

In [79]:
y_pred

array([[44.86053 ],
       [44.865635],
       [44.862408],
       ...,
       [44.860268],
       [44.859188],
       [44.86603 ]], dtype=float32)

In [82]:
y_pred = np.array(y_pred)
y_pred=y_pred.reshape(-1,1)
y_pred.shape

(28251, 1)

In [83]:
y_pred

array([[44.86053 ],
       [44.865635],
       [44.862408],
       ...,
       [44.860268],
       [44.859188],
       [44.86603 ]], dtype=float32)

In [84]:
y_pred

array([[44.86053 ],
       [44.865635],
       [44.862408],
       ...,
       [44.860268],
       [44.859188],
       [44.86603 ]], dtype=float32)

In [85]:
y_test

29467    77.4
4427     51.9
8962     53.0
15981    45.5
23855    43.7
         ... 
5837     50.2
22812    45.6
13207    38.5
20451    48.4
26031    57.7
Name: tm, Length: 28251, dtype: float64

In [86]:
y

14454    50.1
22719    25.0
22279    44.6
31072    38.7
1671     36.0
         ... 
8620     47.9
13147    78.5
4897     64.0
2740     48.8
15954    64.7
Name: tm, Length: 3139, dtype: float64

In [87]:
test = pd.read_csv('test.csv')

In [88]:
test

seq_id                                   protein_sequence  pH  \
0      31390  VPVNPEPDATSVENVAEKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
1      31391  VPVNPEPDATSVENVAKKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2      31392  VPVNPEPDATSVENVAKTGSGDSQSDPIKADLEVKGQSALPFDVDC...   8   
3      31393  VPVNPEPDATSVENVALCTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
4      31394  VPVNPEPDATSVENVALFTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
...      ...                                                ...  ..   
2408   33798  VPVNPEPDATSVENVILKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2409   33799  VPVNPEPDATSVENVLLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2410   33800  VPVNPEPDATSVENVNLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2411   33801  VPVNPEPDATSVENVPLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2412   33802  VPVNPEPDATSVENVWLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   

     data_source  
0      Novozymes  
1      Novozymes  
2      Novozymes  
3      Novozymes  
4      Novozymes  
...          ...  
2408   Novozymes  
2409   Novozymes  
2410   Novozymes  
2411   Novozymes  
2412   Novozymes  

[2413 rows x 4 columns]

In [89]:
test['words'] = test.apply(lambda x: get_kmers_count(x['protein_sequence']), axis = 1)

In [90]:
test

seq_id                                   protein_sequence  pH  \
0      31390  VPVNPEPDATSVENVAEKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
1      31391  VPVNPEPDATSVENVAKKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2      31392  VPVNPEPDATSVENVAKTGSGDSQSDPIKADLEVKGQSALPFDVDC...   8   
3      31393  VPVNPEPDATSVENVALCTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
4      31394  VPVNPEPDATSVENVALFTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
...      ...                                                ...  ..   
2408   33798  VPVNPEPDATSVENVILKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2409   33799  VPVNPEPDATSVENVLLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2410   33800  VPVNPEPDATSVENVNLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2411   33801  VPVNPEPDATSVENVPLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   
2412   33802  VPVNPEPDATSVENVWLKTGSGDSQSDPIKADLEVKGQSALPFDVD...   8   

     data_source                                              words  
0      Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
1      Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
2      Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
3      Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
4      Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
...          ...                                                ...  
2408   Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
2409   Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
2410   Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
2411   Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  
2412   Novozymes  [vpvnpe, pvnpep, vnpepd, npepda, pepdat, epdat...  

[2413 rows x 5 columns]

In [91]:
test_text = list(test['words'])
for item in range(len(test_text)):
    test_text[item]=' '.join(test_text[item])

In [92]:
onehot = [one_hot(words,voc_size) for words in test_text]

In [93]:
max_len = len(max(test['words']))

In [94]:
max_len

215

In [95]:
embedded = pad_sequences(onehot, padding = 'pre', maxlen = 531)

In [96]:
test_data = np.array(embedded)

In [97]:
predictions = model.predict(test_data)

In [98]:
predictions

array([[44.859932],
       [44.859932],
       [44.859932],
       ...,
       [44.859932],
       [44.859932],
       [44.859932]], dtype=float32)

In [57]:
predictions = np.array(predictions)

In [65]:
predictions.shape

(2413, 1)

In [66]:
test_df = test.drop(['protein_sequence', 'pH', 'data_source', 'words'], axis = 1)

In [68]:
test_df['tm'] = predictions

In [69]:
test_df

seq_id         tm
0      31390  44.859932
1      31391  44.859932
2      31392  44.859932
3      31393  44.859932
4      31394  44.859932
...      ...        ...
2408   33798  44.859932
2409   33799  44.859932
2410   33800  44.859932
2411   33801  44.859932
2412   33802  44.859932

[2413 rows x 2 columns]

In [101]:
test_df.to_csv('submission.csv')